### ISSUE TITLE
Orientation changes can cause app to "blank out"

### ISSUE THREAD

**Issue by UrzaMTG** [qklabs/qksms#233]
If QKSMS is left as the active application when the phone screen turns off, changing the orientation of the phone before turning the screen back on can cause the conversation window to go blank. Returning to the list of conversations will blank out that list as well. The problem is fixed by clearing the application from the recent applications list.

This seems to have started as of the October 21st update.

Device: Moto X (2nd Generation)
Android version: 5.1
Carrier: U.S. Cellular

Steps to reproduce:
1. Open QKSMS
2. Open any conversation
3. While in portrait orientation, press the power button on the phone to turn off the screen
4. Rotate the phone to landscape orientation
5. Turn the screen back on (and unlock the device if necessary)
6. Observe the blank conversation screen
7. Use the back button of the phone or the application to return to the conversation list
8. Observe a lack of converstions
9. Use the Recent Applications list to clear QKSMS
10. Re-open QKSMS. All functionality is restored.

**Comment by l3d00m** [comment]
Steps for me are a little bit different:  
Step 1-7 are the same, but I need to rotate back to portrait to blank out all conversations. [picture] (http://i.imgur.com/sseHtzh.png)

**Comment by UrzaMTG** [comment]
So I've found a faster and more consistent way to reproduce the issue.

1. Open a conversation
2. Change orientation five times

**Comment by UrzaMTG** [comment]
Even better, the five orientation changes don't have to be all at once, or in the same conversation. Change orientation one or two times, go to a different conversation, and change a few more times and the issue still occurs.

**Comment by licaon-kter** [comment]
Repro it with 3 orientation changes even ( portrait -> landscape -> portrait -> grayout :( )

**Comment by hafridi** [comment]
For me it's even simpler.
Open app, select conversation, change orientation  and press back and go back to portrait

**Comment by moezbhatti** [comment]
I have really big news! I finally figured out what's causing this. Turns out that this bug is actually the same as the battery drain bug. When you rotate the screen, the CPU usage jumps up and stays there. If you do it a few times, it just stacks higher and higher. Once the CPU usage is above about 90%, then the app isn't able to run the task to load conversations anymore

**Comment by moezbhatti** [comment]
Fixed in https://github.com/qklabs/qksms/commit/3dad335eda9ce18e863b94cedba6428ae4af6ed4

**Comment by UrzaMTG** [comment]
I'd like this to be reopened. I am still encountering this on the currently released build.
